apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170546751
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170546751
    app.kubernetes.io/part-of: test-app-170546751
  name: go-170546751
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170546751
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170546751
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/flt8zapo-tenant/test-app-170546751/go-170546751@sha256:123a2aec819b99a7f6c4d818c9b9ea0986a932ba57fe7a55e065c301a0f80470
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
