apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-170546751
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/flt8zapo-tenant/test-app-170546751/go-170546751@sha256:123a2aec819b99a7f6c4d818c9b9ea0986a932ba57fe7a55e065c301a0f80470
        name: my-go
        resources: {}
status: {}
